
package com.eliyaz.jpm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JPMorganMessageProcessor", targetNamespace = "http://jpm.eliyaz.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JPMorganMessageProcessor {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(action = "addSingleSale")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addSingleSale", targetNamespace = "http://jpm.eliyaz.com/", className = "com.eliyaz.jpm.AddSingleSale")
    @ResponseWrapper(localName = "addSingleSaleResponse", targetNamespace = "http://jpm.eliyaz.com/", className = "com.eliyaz.jpm.AddSingleSaleResponse")
    @Action(input = "addSingleSale", output = "http://jpm.eliyaz.com/JPMorganMessageProcessor/addSingleSaleResponse")
    public boolean addSingleSale(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(action = "addMultipleSales")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addMultipleSales", targetNamespace = "http://jpm.eliyaz.com/", className = "com.eliyaz.jpm.AddMultipleSales")
    @ResponseWrapper(localName = "addMultipleSalesResponse", targetNamespace = "http://jpm.eliyaz.com/", className = "com.eliyaz.jpm.AddMultipleSalesResponse")
    @Action(input = "addMultipleSales", output = "http://jpm.eliyaz.com/JPMorganMessageProcessor/addMultipleSalesResponse")
    public boolean addMultipleSales(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(action = "adjustSales")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adjustSales", targetNamespace = "http://jpm.eliyaz.com/", className = "com.eliyaz.jpm.AdjustSales")
    @ResponseWrapper(localName = "adjustSalesResponse", targetNamespace = "http://jpm.eliyaz.com/", className = "com.eliyaz.jpm.AdjustSalesResponse")
    @Action(input = "adjustSales", output = "http://jpm.eliyaz.com/JPMorganMessageProcessor/adjustSalesResponse")
    public boolean adjustSales(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
